/* eslint-disable max-lines */
import { digest } from "../core/brands";
import { egressClass } from "../placement/egress";
import type { BundledComponentDescriptor } from "./types";

export { loadAgentSkillPackages, loadBundledPackages } from "./bundled";
export {
  assertBrokeredDestination,
  assertWorkspacePath,
  stripActiveContent,
} from "./guards";

const descriptor = (
  input: BundledComponentDescriptor,
): BundledComponentDescriptor => Object.freeze(input);

const browserCompanion = Object.freeze({
  name: "chromium",
  image: "ghcr.io/elliott/agent-browser@sha256:bundled",
  egress: egressClass("declared"),
  endpoint: "cdp",
  tmpfs: Object.freeze(["/profile"]),
  secretRefs: Object.freeze([]),
  manifestDigest: digest("sha256:bundled-browser"),
});

const cloudflaredCompanion = Object.freeze({
  name: "cloudflared",
  image: "cloudflare/cloudflared@sha256:bundled",
  egress: egressClass("declared", ["cloudflare-edge"]),
  endpoint: "webhook-only",
  tmpfs: Object.freeze([]),
  secretRefs: Object.freeze(["secret://gateways/cloudflared/tunnel-token"]),
  manifestDigest: digest("sha256:bundled-cloudflared"),
});

export const BUNDLED_CATALOG: readonly BundledComponentDescriptor[] = Object
  .freeze([
    descriptor({
      name: "code-review",
      kind: "skill",
      protocols: ["prompt.source"],
      egress: egressClass("none"),
      isolation: "container",
      secretRefs: [],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "debugging",
      kind: "skill",
      protocols: ["prompt.source"],
      egress: egressClass("none"),
      isolation: "container",
      secretRefs: [],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "research",
      kind: "skill",
      protocols: ["prompt.source"],
      egress: egressClass("none"),
      isolation: "container",
      secretRefs: [],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "search-duckduckgo",
      kind: "tool",
      protocols: ["search.provider"],
      egress: egressClass("declared", ["duckduckgo.com"]),
      isolation: "container",
      secretRefs: [],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "search-brave",
      kind: "tool",
      protocols: ["search.provider"],
      egress: egressClass("declared", ["api.search.brave.com"]),
      isolation: "container",
      secretRefs: ["secret://search/brave/api-key"],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "web-firecrawl",
      kind: "tool",
      protocols: ["search.provider", "content.extractor"],
      egress: egressClass("declared", ["api.firecrawl.dev"]),
      isolation: "container",
      secretRefs: ["secret://web/firecrawl/api-key"],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "web-parallel",
      kind: "tool",
      protocols: ["search.provider", "content.extractor"],
      egress: egressClass("declared", ["api.parallel.ai"]),
      isolation: "container",
      secretRefs: ["secret://web/parallel/api-key"],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "browser",
      kind: "extension",
      protocols: ["tool.executor"],
      egress: egressClass("declared"),
      isolation: "container",
      secretRefs: [],
      senderAllowlistRequired: false,
      untrustedOutput: true,
      companion: browserCompanion,
    }),
    descriptor({
      name: "mcp-client",
      kind: "mcp-endpoint",
      protocols: ["tool.executor", "resource.reader", "prompt.source"],
      egress: egressClass("declared"),
      isolation: "container",
      secretRefs: [],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "gateway-slack",
      kind: "gateway",
      protocols: ["message.source", "message.sink", "identity.resolver"],
      egress: egressClass("declared", ["slack.com", "slack-edge.com"]),
      isolation: "container",
      secretRefs: [
        "secret://gateways/slack/bot-token",
        "secret://gateways/slack/app-token",
        "secret://gateways/slack/user-token",
      ],
      senderAllowlistRequired: true,
      untrustedOutput: true,
    }),
    descriptor({
      name: "gateway-email",
      kind: "gateway",
      protocols: ["message.source", "message.sink"],
      egress: egressClass("declared", ["mail-hosts"]),
      isolation: "container",
      secretRefs: ["secret://gateways/email/credentials"],
      senderAllowlistRequired: true,
      untrustedOutput: true,
    }),
    descriptor({
      name: "gateway-gmail",
      kind: "gateway",
      protocols: ["message.source", "message.sink"],
      egress: egressClass("declared", ["googleapis.com"]),
      isolation: "container",
      secretRefs: ["secret://gateways/gmail/refresh-token"],
      senderAllowlistRequired: true,
      untrustedOutput: true,
    }),
    descriptor({
      name: "gateway-webhook",
      kind: "gateway",
      protocols: ["message.source"],
      egress: egressClass("none"),
      isolation: "container",
      secretRefs: ["secret://gateways/webhook/signing-secret"],
      senderAllowlistRequired: true,
      untrustedOutput: true,
    }),
    descriptor({
      name: "cloudflared",
      kind: "extension",
      protocols: ["health.checker"],
      egress: egressClass("declared", ["cloudflare-edge"]),
      isolation: "container",
      secretRefs: ["secret://gateways/cloudflared/tunnel-token"],
      senderAllowlistRequired: false,
      untrustedOutput: false,
      companion: cloudflaredCompanion,
    }),
    descriptor({
      name: "gateway-home-assistant",
      kind: "gateway",
      protocols: ["message.source", "message.sink", "tool.executor"],
      egress: egressClass("lan"),
      isolation: "container",
      secretRefs: ["secret://gateways/home-assistant/token"],
      senderAllowlistRequired: true,
      untrustedOutput: true,
    }),
    descriptor({
      name: "gateway-bluebubbles",
      kind: "gateway",
      protocols: ["message.source", "message.sink"],
      egress: egressClass("lan"),
      isolation: "remote",
      secretRefs: ["secret://gateways/bluebubbles/password"],
      senderAllowlistRequired: true,
      untrustedOutput: true,
    }),
    descriptor({
      name: "scheduler",
      kind: "scheduler",
      protocols: ["scheduler"],
      egress: egressClass("none"),
      isolation: "container",
      secretRefs: [],
      senderAllowlistRequired: false,
      untrustedOutput: false,
    }),
    descriptor({
      name: "evaluator-dspy",
      kind: "evaluator",
      protocols: ["optimization.engine", "evaluation.runner"],
      egress: egressClass("none"),
      isolation: "container",
      secretRefs: [],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "evaluator-darwinian",
      kind: "evaluator",
      protocols: ["optimization.engine"],
      egress: egressClass("none"),
      isolation: "container",
      secretRefs: [],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "evaluator-agent-benchmarks",
      kind: "evaluator",
      protocols: ["benchmark.runner"],
      egress: egressClass("none"),
      isolation: "container",
      secretRefs: [],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "files",
      kind: "tool",
      protocols: ["resource.reader", "resource.writer"],
      egress: egressClass("none"),
      isolation: "container",
      secretRefs: [],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "terminal",
      kind: "tool",
      protocols: ["tool.executor"],
      egress: egressClass("none"),
      isolation: "container",
      secretRefs: [],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "ssh",
      kind: "tool",
      protocols: ["tool.executor"],
      egress: egressClass("declared"),
      isolation: "container",
      secretRefs: ["secret://tools/ssh/private-key"],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "pihole",
      kind: "tool",
      protocols: ["tool.executor"],
      egress: egressClass("lan"),
      isolation: "container",
      secretRefs: ["secret://tools/pihole/password"],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "subscription-usage",
      kind: "tool",
      protocols: ["tool.executor"],
      egress: egressClass("declared", [
        "api.anthropic.com",
        "console.anthropic.com",
        "chatgpt.com",
        "auth.openai.com",
        "api.litellm.octet.stream",
      ]),
      isolation: "container",
      secretRefs: ["secret://tools/subscription-usage/accounts"],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "traefik",
      kind: "extension",
      protocols: ["tool.executor"],
      egress: egressClass("lan"),
      isolation: "container",
      secretRefs: [],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "webhook-provisioner",
      kind: "extension",
      protocols: ["facility.provider"],
      egress: egressClass("none"),
      isolation: "container",
      secretRefs: ["secret://facilities/webhook"],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "fetch",
      kind: "tool",
      protocols: ["tool.executor"],
      egress: egressClass("declared"),
      isolation: "container",
      secretRefs: [],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "deep-trace",
      kind: "extension",
      protocols: ["health.checker"],
      egress: egressClass("none"),
      isolation: "container",
      secretRefs: [],
      senderAllowlistRequired: false,
      untrustedOutput: false,
    }),
    descriptor({
      name: "news-brief",
      kind: "extension",
      protocols: ["content.extractor"],
      egress: egressClass("declared", [
        "www.reddit.com",
        "content.guardianapis.com",
        "feeds.bbci.co.uk",
        "feeds.apnews.com",
        "feeds.reuters.com",
        "newsdata.io",
        "gnews.io",
      ]),
      isolation: "container",
      secretRefs: [
        "secret://news-brief/guardian/api-key",
        "secret://news-brief/newsdata/api-key",
        "secret://news-brief/gnews/api-key",
      ],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "pakman-latest-episode",
      kind: "tool",
      protocols: ["content.extractor"],
      egress: egressClass("declared", [
        "www.davidpakman.com",
        "davidpakman.com",
      ]),
      isolation: "container",
      secretRefs: ["secret://pakman/credentials"],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "youtube-dvr",
      kind: "extension",
      protocols: ["tool.executor"],
      egress: egressClass("declared", [
        "youtube.googleapis.com",
        "oauth2.googleapis.com",
      ]),
      isolation: "container",
      secretRefs: ["secret://youtube/oauth"],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
  ]);

export type * from "./types";
