import { egressClass } from "../placement/egress";
import type { BundledComponentDescriptor } from "./types";

export { loadAgentSkillPackages, loadBundledPackages } from "./bundled";
export {
  assertBrokeredDestination,
  assertWorkspacePath,
  stripActiveContent,
} from "./guards";

const descriptor = (
  input: BundledComponentDescriptor,
): BundledComponentDescriptor => Object.freeze(input);

export const BUNDLED_CATALOG: readonly BundledComponentDescriptor[] = Object
  .freeze([
    descriptor({
      name: "mcp-client",
      kind: "mcp-endpoint",
      protocols: ["tool.executor", "resource.reader", "prompt.source"],
      egress: egressClass("declared"),
      isolation: "container",
      secretRefs: [],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "scheduler",
      kind: "scheduler",
      protocols: ["scheduler"],
      egress: egressClass("none"),
      isolation: "container",
      secretRefs: [],
      senderAllowlistRequired: false,
      untrustedOutput: false,
    }),
    descriptor({
      name: "evaluator-dspy",
      kind: "evaluator",
      protocols: ["optimization.engine", "evaluation.runner"],
      egress: egressClass("none"),
      isolation: "container",
      secretRefs: [],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "evaluator-darwinian",
      kind: "evaluator",
      protocols: ["optimization.engine"],
      egress: egressClass("none"),
      isolation: "container",
      secretRefs: [],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "evaluator-agent-benchmarks",
      kind: "evaluator",
      protocols: ["benchmark.runner"],
      egress: egressClass("none"),
      isolation: "container",
      secretRefs: [],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "files",
      kind: "tool",
      protocols: ["resource.reader", "resource.writer"],
      egress: egressClass("none"),
      isolation: "container",
      secretRefs: [],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "terminal",
      kind: "tool",
      protocols: ["tool.executor"],
      egress: egressClass("none"),
      isolation: "container",
      secretRefs: [],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "ssh",
      kind: "tool",
      protocols: ["tool.executor"],
      egress: egressClass("declared"),
      isolation: "container",
      secretRefs: ["secret://tools/ssh/private-key"],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "fetch",
      kind: "tool",
      protocols: ["tool.executor"],
      egress: egressClass("declared"),
      isolation: "container",
      secretRefs: [],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "deep-trace",
      kind: "extension",
      protocols: ["health.checker"],
      egress: egressClass("none"),
      isolation: "container",
      secretRefs: [],
      senderAllowlistRequired: false,
      untrustedOutput: false,
    }),
    descriptor({
      name: "glitchtip",
      kind: "extension",
      protocols: ["health.checker"],
      egress: egressClass("declared"),
      isolation: "container",
      secretRefs: [],
      senderAllowlistRequired: false,
      untrustedOutput: false,
    }),
    descriptor({
      name: "vault",
      kind: "tool",
      protocols: ["tool.executor"],
      egress: egressClass("declared"),
      isolation: "container",
      secretRefs: ["secret://tools/vault/token"],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "gateway-bluebubbles",
      kind: "gateway",
      protocols: ["message.source", "message.sink", "identity.resolver"],
      egress: egressClass("lan"),
      isolation: "remote",
      secretRefs: ["secret://gateways/bluebubbles"],
      senderAllowlistRequired: true,
      untrustedOutput: true,
    }),
    descriptor({
      name: "gateway-email",
      kind: "tool",
      protocols: ["message.sink"],
      egress: egressClass("declared"),
      isolation: "container",
      secretRefs: ["secret://gateways/email"],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "gateway-gmail",
      kind: "gateway",
      protocols: ["message.source", "message.sink", "identity.resolver"],
      egress: egressClass("declared"),
      isolation: "container",
      secretRefs: ["secret://gateways/gmail"],
      senderAllowlistRequired: true,
      untrustedOutput: true,
    }),
    descriptor({
      name: "gateway-slack",
      kind: "gateway",
      protocols: ["message.source", "message.sink", "identity.resolver"],
      egress: egressClass("declared", [
        "slack.com",
        "slack-edge.com",
        "hooks.slack.com",
      ]),
      isolation: "container",
      secretRefs: ["secret://gateways/slack", "secret://facilities/webhook"],
      senderAllowlistRequired: true,
      untrustedOutput: true,
    }),
    descriptor({
      name: "gateway-webhook",
      kind: "gateway",
      protocols: ["message.source", "identity.resolver"],
      egress: egressClass("none"),
      isolation: "container",
      secretRefs: ["secret://gateways/webhook"],
      senderAllowlistRequired: true,
      untrustedOutput: true,
    }),
    descriptor({
      name: "search-brave",
      kind: "tool",
      protocols: ["search.provider"],
      egress: egressClass("declared", ["api.search.brave.com"]),
      isolation: "container",
      secretRefs: ["secret://search/brave/api-key"],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "search-duckduckgo",
      kind: "tool",
      protocols: ["search.provider"],
      egress: egressClass("declared", ["html.duckduckgo.com"]),
      isolation: "container",
      secretRefs: [],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "web-firecrawl",
      kind: "tool",
      protocols: ["search.provider", "content.extractor"],
      egress: egressClass("declared", ["api.firecrawl.dev"]),
      isolation: "container",
      secretRefs: ["secret://web/firecrawl/api-key"],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "web-parallel",
      kind: "tool",
      protocols: ["search.provider", "content.extractor"],
      egress: egressClass("declared", ["api.parallel.ai"]),
      isolation: "container",
      secretRefs: ["secret://web/parallel/api-key"],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "traefik",
      kind: "extension",
      protocols: ["tool.executor"],
      egress: egressClass("lan"),
      isolation: "container",
      secretRefs: [],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
    descriptor({
      name: "webhook-provisioner",
      kind: "extension",
      protocols: ["facility.provider"],
      egress: egressClass("loopback"),
      isolation: "container",
      secretRefs: ["secret://facilities/webhook"],
      senderAllowlistRequired: false,
      untrustedOutput: true,
    }),
  ]);

export type * from "./types";
