import type { InboundContextEntity } from "../../../../src/runtime/types";
import type { SlackJson } from "./types";

export const FEEDBACK_ACTION_ID = "elliott_feedback";
export const DELETE_ACTION_ID = "elliott_delete";

const DISCLAIMER =
  "This response was generated by AI and may be inaccurate. Review it before acting.";
const MAX_SUGGESTED_PROMPTS = 4;

export const markdownBlock = (text: string): SlackJson => ({
  type: "markdown",
  text,
});

export const responseFooterBlocks = (): readonly SlackJson[] => [
  {
    type: "context",
    block_id: "elliott_ai_disclaimer",
    elements: [{ type: "mrkdwn", text: DISCLAIMER }],
  },
  {
    type: "context_actions",
    block_id: "elliott_response_actions",
    elements: [
      {
        type: "feedback_buttons",
        action_id: FEEDBACK_ACTION_ID,
        positive_button: {
          text: { type: "plain_text", text: "Helpful" },
          accessibility_label: "Mark this response as helpful",
          value: "positive",
        },
        negative_button: {
          text: { type: "plain_text", text: "Not helpful" },
          accessibility_label: "Mark this response as not helpful",
          value: "negative",
        },
      },
      {
        type: "icon_button",
        icon: "trash",
        text: { type: "plain_text", text: "Delete" },
        accessibility_label: "Delete this response",
        action_id: DELETE_ACTION_ID,
        value: "delete",
      },
    ],
  },
];

export const agentMessageBlocks = (text: string): readonly SlackJson[] => [
  markdownBlock(text),
  ...responseFooterBlocks(),
];

export const welcomeBlocks = (): readonly SlackJson[] => [
  {
    type: "header",
    text: { type: "plain_text", text: "Elliott is ready" },
  },
  {
    type: "section",
    expand: true,
    text: {
      type: "mrkdwn",
      text:
        "Ask me to research, plan, operate your connected tools, or work from what you're viewing in Slack. I’ll show progress as I work and cite Slack sources when I use them.",
    },
  },
  ...responseFooterBlocks(),
];

export const suggestedPrompts = (
  context: readonly InboundContextEntity[],
): readonly SlackJson[] => {
  const contextual = context.length === 0
    ? []
    : [{
      title: "Work from this context",
      message:
        "Use the Slack context I’m currently viewing to summarize what matters and suggest next actions.",
    }];
  return [
    ...contextual,
    {
      title: "Find something in Slack",
      message:
        "Search Slack for the latest relevant information about a topic I’ll provide.",
    },
    {
      title: "Plan a task",
      message:
        "Help me turn a goal into a concrete plan, then carry out the steps I approve.",
    },
    {
      title: "What can you do?",
      message:
        "Give me a concise overview of what you can do and which connected tools you can use.",
    },
  ].slice(0, MAX_SUGGESTED_PROMPTS);
};

export const withResponseFooters = (
  blocks: readonly SlackJson[],
): readonly SlackJson[] => [
  ...blocks.filter((block) =>
    block["block_id"] !== "elliott_ai_disclaimer"
    && block["block_id"] !== "elliott_response_actions"
  ),
  ...responseFooterBlocks(),
];
